# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registred', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_table',
            new_name='admin_register_table',
        ),
    ]
