# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registred', '0002_auto_20200802_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_register_table',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
