# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('check_in', models.CharField(max_length=100)),
                ('check_out', models.CharField(max_length=100)),
                ('members', models.IntegerField()),
            ],
        ),
    ]
